on:
  push:
    branches:
    - main
    - release/*
jobs:
  trigger_build_and_deploy:
    name: Trigger build and deploy
    runs-on: ubuntu-22.04
    steps:
    - name: Trigger jenkins job
      run: curl -X POST -u "goju2k:$RIBS_JENKINS_KEY" "http://www.ribs.kr:10000/job/build-ribs-home/build"
